services:
  db:
    image: postgres:16-alpine
    container_name: food_delivery_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-food_delivery_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-food_delivery_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - food_delivery_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: food_delivery_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - food_delivery_net

  # --- Redis Setup ---

  redis:
    image: redis:7.2-alpine
    container_name: food_delivery_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

    # 'save 60 1' ensures data persists to disk if 1 key changes every 60s
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - food_delivery_net

  # --- Redis UI ---
  redis-insight:
    image: redis/redisinsight:latest
    container_name: food_delivery_redis_insight
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - food_delivery_net


  # --- Kafka Message Broker ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: food_delivery_kafka
    ports:
      - "9092:9092"

    volumes:
      - kafka_data:/var/lib/kafka/data

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 127.0.0.1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      #  This generates a random, valid Kafka Cluster ID
      #  docker run --rm confluentinc/cp-kafka:7.5.0 kafka-storage random-uuid
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - food_delivery_net

  # --- Kafka UI (Crucial for Debugging) ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: food_delivery_kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      kafka:
        condition: service_healthy

    networks:
      - food_delivery_net

networks:
  food_delivery_net:
    driver: bridge

volumes:
  postgres_data:
  kafka_data:
  redis_data: