[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       app_json
    Preserve_Key On
    Reserve_Data On

[OUTPUT]
    Name         es
    Match        *
    Host         elasticsearch
    Port         9200
    Index        food-delivery-stream-logs
    Logstash_Format On
    Retry_Limit  False
    Suppress_Type_Name On
