"""add modified order item table

Revision ID: f20bd08f6f63
Revises: e25e08307c91
Create Date: 2026-03-28 19:41:47.882178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f20bd08f6f63"
down_revision: Union[str, Sequence[str], None] = "e25e08307c91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items",
        sa.Column("discount_amount", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.add_column("order_items", sa.Column("instructions", sa.String(length=500), nullable=True))
    op.add_column(
        "order_items",
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.alter_column(
        "order_items",
        "product_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="product_id::uuid",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_items",
        "product_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("order_items", "metadata")
    op.drop_column("order_items", "instructions")
    op.drop_column("order_items", "discount_amount")
    # ### end Alembic commands ###
